import React from "react";
import ReactDom from "react-dom";
// import "./ticTacToe/style.css";
// import Game from "./ticTacToe/Game";
// ReactDom.render(<Game />, document.getElementById("root"));
// import ArrayEx from "./variousExercises/ArrayEx";
// import "./cyclic/style.css";
// import Cyclic from "./cyclic/Cyclic";
import Skocko from "./skocko/Skocko";
import "./skocko/style.css";
ReactDom.render(<Skocko />, document.getElementById("root"));
